// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: MessageToClient.proto

#include "MessageToClient.pb.h"
#include "MessageToClient.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace hello {

static const char* RemoteAdd_method_names[] = {
  "/hello.RemoteAdd/GetResult",
  "/hello.RemoteAdd/GetNumberSequence",
};

std::unique_ptr< RemoteAdd::Stub> RemoteAdd::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< RemoteAdd::Stub> stub(new RemoteAdd::Stub(channel, options));
  return stub;
}

RemoteAdd::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetResult_(RemoteAdd_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetNumberSequence_(RemoteAdd_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  {}

::grpc::Status RemoteAdd::Stub::GetResult(::grpc::ClientContext* context, const ::hello::Adder& request, ::hello::Result* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hello::Adder, ::hello::Result, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetResult_, context, request, response);
}

void RemoteAdd::Stub::async::GetResult(::grpc::ClientContext* context, const ::hello::Adder* request, ::hello::Result* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hello::Adder, ::hello::Result, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetResult_, context, request, response, std::move(f));
}

void RemoteAdd::Stub::async::GetResult(::grpc::ClientContext* context, const ::hello::Adder* request, ::hello::Result* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetResult_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hello::Result>* RemoteAdd::Stub::PrepareAsyncGetResultRaw(::grpc::ClientContext* context, const ::hello::Adder& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hello::Result, ::hello::Adder, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetResult_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hello::Result>* RemoteAdd::Stub::AsyncGetResultRaw(::grpc::ClientContext* context, const ::hello::Adder& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetResultRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReader< ::hello::Number>* RemoteAdd::Stub::GetNumberSequenceRaw(::grpc::ClientContext* context, const ::hello::NumberPair& request) {
  return ::grpc::internal::ClientReaderFactory< ::hello::Number>::Create(channel_.get(), rpcmethod_GetNumberSequence_, context, request);
}

void RemoteAdd::Stub::async::GetNumberSequence(::grpc::ClientContext* context, const ::hello::NumberPair* request, ::grpc::ClientReadReactor< ::hello::Number>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::hello::Number>::Create(stub_->channel_.get(), stub_->rpcmethod_GetNumberSequence_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::hello::Number>* RemoteAdd::Stub::AsyncGetNumberSequenceRaw(::grpc::ClientContext* context, const ::hello::NumberPair& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::hello::Number>::Create(channel_.get(), cq, rpcmethod_GetNumberSequence_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::hello::Number>* RemoteAdd::Stub::PrepareAsyncGetNumberSequenceRaw(::grpc::ClientContext* context, const ::hello::NumberPair& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::hello::Number>::Create(channel_.get(), cq, rpcmethod_GetNumberSequence_, context, request, false, nullptr);
}

RemoteAdd::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RemoteAdd_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RemoteAdd::Service, ::hello::Adder, ::hello::Result, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RemoteAdd::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hello::Adder* req,
             ::hello::Result* resp) {
               return service->GetResult(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RemoteAdd_method_names[1],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< RemoteAdd::Service, ::hello::NumberPair, ::hello::Number>(
          [](RemoteAdd::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hello::NumberPair* req,
             ::grpc::ServerWriter<::hello::Number>* writer) {
               return service->GetNumberSequence(ctx, req, writer);
             }, this)));
}

RemoteAdd::Service::~Service() {
}

::grpc::Status RemoteAdd::Service::GetResult(::grpc::ServerContext* context, const ::hello::Adder* request, ::hello::Result* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RemoteAdd::Service::GetNumberSequence(::grpc::ServerContext* context, const ::hello::NumberPair* request, ::grpc::ServerWriter< ::hello::Number>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace hello

